### ISSUE TITLE
Example to run w/ custom data

### ISSUE THREAD

**Issue by hai-h-nguyen** [stanford-iprl-lab/torchfilter#3]
Hi, great repo! I am trying to learn a particle filter with my custom domain. I can generate trajectories of a certain length that contain pairs of (observation, action, true-state). How do I proceed w/ training a filter from here using this repo?

**Comment by brentyi** [comment]
Hey there! Apologies for missing this.

All of the models and filters in this repository are implemented as standard PyTorch modules, so any standard supervised-learning training loop should work. We don't prescribe anything specific.

There are some [example training helpers](https://github.com/stanford-iprl-lab/torchfilter/tree/master/torchfilter/train) in the repo. These are tied into a custom experiment management framework and might be better as references, but the framework is pretty lightweight and doesn't require any setup work if you want to give it a stab. For pared-down usage, you can look at our [single-component training tests](https://github.com/stanford-iprl-lab/torchfilter/blob/master/tests/test_train_component.py) or [end-to-end training tests](https://github.com/stanford-iprl-lab/torchfilter/blob/master/tests/test_train_e2e.py). A full-system example lives in [the training scripts](https://github.com/brentyi/multimodalfilter/blob/master/scripts/push_task/train_push.py) we used to generate results that are presented in our IROS 2020 paper.
