### ISSUE TITLE
Cannot install the package properly

### ISSUE THREAD

**Issue by xEnVrE** [stanford-iprl-lab/torchfilter#4]
Dear authors of the code,

I tried to install the code provided by this repository using

```
pip install -e .
```

but it seems that your `setup.py` is not working as expected, at least for my configuration with `Python 3.7.9`.

Indeed, the resulting installation folder  `(...)/lib/python3.7/site-packages/torchfilter` only contains

```
__init__.py  __pycache__  types.py
```

and is missing all the other submodules `base`, `data`, `filters`, `train` and `utils`.

I solved by changing

https://github.com/stanford-iprl-lab/torchfilter/blob/94a58878959a8aeb7097f2e4e37c13af1c543479/setup.py#L1

to `from setuptools import setup, find_packages`

and 

https://github.com/stanford-iprl-lab/torchfilter/blob/94a58878959a8aeb7097f2e4e37c13af1c543479/setup.py#L11

to `packages=find_packages()`. 

`find_packages` will take care of all the submodules.

**Comment by brentyi** [comment]
@xEnVrE thanks for the detailed report! I was able to reproduce this, though I had to omit the `-e` flag in the `pip install` command.

Just patched the test infrastructure and pushed the fix you recommended. :slightly_smiling_face:

**Comment by xEnVrE** [comment]
Thank you @brentyi
